if you have 3 categories to har category ke lia alag col bna dete ho

Dummy variable traf ji me ap apne pass encodine ke bad n-1 cols hi rkhte ho like 10 cols to generally first col haa dete ho

In [ ]:
# in machin learning this is general wisdom that input cols must not have any relation to multicolinearity ko remove krne ke lia krna chahie.
# linear models me yh issues krte hn
# ohe using most frequent category

In [28]:
import numpy as np
import pandas as pd #data processing
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df=pd.read_csv("cars_2000_rows.csv")

In [30]:
df.columns

Index(['Brand', 'Color', 'Fuel_Type', 'Transmission', 'Price'], dtype='object')

In [31]:
df["Brand"].value_counts()
df["Fuel_Type"].value_counts()
df["Color"].value_counts()
df["Transmission"].value_counts()

Transmission
Manual       1004
Automatic     996
Name: count, dtype: int64

Encoding using pandas

In [18]:
pd.get_dummies(df, columns=['Fuel_Type', 'Color', 'Transmission'])

,Brand,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Red,Color_Silver,Color_White,Color_Yellow,Transmission_Automatic,Transmission_Manual
0,Honda,29628,False,True,False,False,False,False,False,False,True,False,False,False,False,True
1,Ford,17082,False,False,False,True,False,True,False,False,False,False,False,False,True,False
2,Toyota,48118,True,False,False,False,False,True,False,False,False,False,False,False,False,True
3,Mercedes,29446,True,False,False,False,False,False,False,False,True,False,False,False,True,False
4,Nissan,60753,False,False,False,True,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Nissan,34757,False,False,False,True,False,True,False,False,False,False,False,False,True,False
1996,Nissan,23377,True,False,False,False,False,False,False,False,False,False,True,False,False,True
1997,BMW,73649,False,True,False,False,False,False,False,True,False,False,False,False,True,False
1998,Kia,19437,False,False,False,True,False,False,False,False,False,False,False,True,True,False
1999,Nissan,54266,False,False,False,True,False,False,False,True,False,False,False,False,False,True

In [19]:
# k hot encoding
pd.get_dummies(df, columns=['Fuel_Type', 'Color', 'Transmission'], drop_first=True) # drop first column to avoid multicolinearity

,Brand,Price,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Color_Blue,Color_Gray,Color_Green,Color_Red,Color_Silver,Color_White,Color_Yellow,Transmission_Manual
0,Honda,29628,True,False,False,False,False,False,True,False,False,False,True
1,Ford,17082,False,False,True,True,False,False,False,False,False,False,False
2,Toyota,48118,False,False,False,True,False,False,False,False,False,False,True
3,Mercedes,29446,False,False,False,False,False,False,True,False,False,False,False
4,Nissan,60753,False,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Nissan,34757,False,False,True,True,False,False,False,False,False,False,False
1996,Nissan,23377,False,False,False,False,False,False,False,False,True,False,True
1997,BMW,73649,True,False,False,False,False,True,False,False,False,False,False
1998,Kia,19437,False,False,True,False,False,False,False,False,False,True,False
1999,Nissan,54266,False,False,True,False,False,True,False,False,False,False,True

Pandas donot remember the column sequence

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[["Brand", 'Color', 'Fuel_Type', 'Transmission']], df["Price"], test_size=0.3)
x_train, x_test

(        Brand   Color Fuel_Type Transmission
 286       Kia   Black    Hybrid       Manual
 1427     Ford     Red    Petrol       Manual
 631     Honda    Gray    Petrol       Manual
 991    Toyota     Red    Hybrid       Manual
 751   Hyundai  Silver  Electric       Manual
 ...       ...     ...       ...          ...
 1074  Hyundai   Green    Diesel       Manual
 1398     Ford   White  Electric       Manual
 1122      BMW   Green    Petrol    Automatic
 1475     Ford    Blue    Diesel       Manual
 365      Audi   Black    Diesel    Automatic

 [1400 rows x 4 columns],
         Brand   Color Fuel_Type Transmission
 1014    Honda   Black    Petrol    Automatic
 1017     Ford     Red  Electric    Automatic
 976   Hyundai     Red    Hybrid       Manual
 41     Suzuki    Gray    Hybrid    Automatic
 510   Hyundai  Yellow    Hybrid       Manual
 ...       ...     ...       ...          ...
 270   Hyundai  Yellow  Electric       Manual
 872       BMW   Black    Hybrid    Automatic
 520    Suzuki   Green    Petrol       Manual
 1080   Suzuki   Green  Electric    Automatic
 805    Nissan    Blue    Hybrid    Automatic

 [600 rows x 4 columns])

In [38]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe.fit(x_train[['Brand', 'Color', 'Fuel_Type', 'Transmission']])
x_train_new=ohe.transform(x_train[['Brand', 'Color', 'Fuel_Type', 'Transmission']]).toarray()
x_test_new=ohe.transform(x_test[['Brand', 'Color', 'Fuel_Type', 'Transmission']]).toarray()

In [ ]:
# since you are not encoding all the columns so after encoding you have to merge the prvious/ rem cols with new cols

In [ ]:
# np.hstack((#pass both here))

Droping the col that has many rows

In [46]:
counts= df["Brand"].value_counts()
threshold=200
repl= counts[counts <= threshold].index

In [47]:
pd.get_dummies(df["Brand"].replace(repl, "uncommon"))

        BMW  Honda  Hyundai    Kia  Nissan  Suzuki  uncommon
0     False   True    False  False   False   False     False
1     False  False    False  False   False   False      True
2     False  False    False  False   False   False      True
3     False  False    False  False   False   False      True
4     False  False    False  False    True   False     False
...     ...    ...      ...    ...     ...     ...       ...
1995  False  False    False  False    True   False     False
1996  False  False    False  False    True   False     False
1997   True  False    False  False   False   False     False
1998  False  False    False   True   False   False     False
1999  False  False    False  False    True   False     False

[2000 rows x 7 columns]