In [ ]:
import pandas as pd
pd.read_excel("Birman_Cats_Dataset.xlsx", index_col="Cat_ID")
# if you want anyother sheet then you have to use the parameter sheet_name="sheet2"

              Name  Age_Years       Coat_Color      Eye_Color
Cat_ID
1       Birman_001          1       Seal Point           Blue
2       Birman_002          2       Blue Point      Deep Blue
3       Birman_003          3  Chocolate Point  Sapphire Blue
4       Birman_004          4      Lilac Point           Blue
5       Birman_005          5      Cream Point      Deep Blue
...            ...        ...              ...            ...
96      Birman_096          6       Seal Point  Sapphire Blue
97      Birman_097          7       Blue Point           Blue
98      Birman_098          8  Chocolate Point      Deep Blue
99      Birman_099          9      Lilac Point  Sapphire Blue
100     Birman_100         10      Cream Point           Blue

[100 rows x 4 columns]

Text files

In [4]:
# text files open in any text editor anylyze it how this is arranges 
# like arranged in tabular form as tab seperated
import pandas as pd
pd.read_csv("Birman_Cats_Dataset_100_Rows.txt", sep="/'/' "  )

C:\Users\mobee\AppData\Local\Temp\ipykernel_19000\1902568328.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv("Birman_Cats_Dataset_100_Rows.txt", sep="/'/' "  )

    Cat_ID  Name    Age_Years   Coat_Color  Eye_Color
0                1   Birman_001  1   Seal Point  Blue
1           2   Birman_002  2   Blue Point  Deep Blue
2   3   Birman_003  3   Chocolate Point Sapphire Blue
3                4   Birman_004  4   Lilac Point Blue
4           5   Birman_005  5   Cream Point Deep Blue
..                                                ...
95      96  Birman_096  6   Seal Point  Sapphire Blue
96               97  Birman_097  7   Blue Point  Blue
97      98  Birman_098  8   Chocolate Point Deep Blue
98      99  Birman_099  9   Lilac Point Sapphire Blue
99               100 Birman_100  10  Cream Point Blue

[100 rows x 1 columns]

JSON

In [5]:
# server API WAPIS DATA LA KR DETA HAI AS JSON
# SQL (structured query language)-> basically ap database se la rhe ho
import pandas as pd
pd.read_json("Birman_Cats_Dataset_100_Rows.json")

    Cat_ID        Name  Age_Years       Coat_Color      Eye_Color
0        1  Birman_001          1       Seal Point           Blue
1        2  Birman_002          2       Blue Point      Deep Blue
2        3  Birman_003          3  Chocolate Point  Sapphire Blue
3        4  Birman_004          4      Lilac Point           Blue
4        5  Birman_005          5      Cream Point      Deep Blue
..     ...         ...        ...              ...            ...
95      96  Birman_096          6       Seal Point  Sapphire Blue
96      97  Birman_097          7       Blue Point           Blue
97      98  Birman_098          8  Chocolate Point      Deep Blue
98      99  Birman_099          9      Lilac Point  Sapphire Blue
99     100  Birman_100         10      Cream Point           Blue

[100 rows x 5 columns]

SQL

In [ ]:
# you need xampp
# then go to localhost/phpmyadmin/
# create new database
# then import the dataset
# after runnng there you have to convert your sql dataset into pandas dataframe
# you have to connect sql with pandas using library
# pip install mysql.connector

# import mysql.connector
# conn= mysql.connector.connection(host="localhost", user="root", password=" ", database=" name of database") 
# this above line returns a connection object on which you prceed your work
# pd.read_sql_query("query", conn(connection object))