In [349]:
import pandas as pd
import numpy as np

### CLEANING OF monthly_targets_dirty.csv

In [350]:
mt=pd.read_csv("monthly_targets_dirty.csv")
mt.columns=mt.columns.str.lower().str.strip().str.replace(" ", "_")
mt.columns

Index(['month', 'region', 'category', 'sales_target', 'target_margin_%'], dtype='object')

In [351]:
mt["region"] = mt["region"].str.lower().str.strip()
mt.replace(["","unknown","?","missing"], np.nan, inplace=True)
mt["region"].value_counts()
mt = mt.dropna(subset=["region"])
mt["region"].isna().sum()

np.int64(0)

In [352]:
mt["category"]=mt["category"].str.lower().str.strip()
mt["category"] = mt["category"].replace("", np.nan)
mt=mt.dropna(subset=["category"])

In [353]:
mt["month"] = (
    mt["month"]
    .str.strip()
    .pipe(pd.to_datetime, errors="coerce")
)

In [354]:
mt=mt.dropna(subset=["month"])

In [355]:
col=mt["target_margin_%"].astype(str).str.strip()
is_percent=mt["target_margin_%"].str.contains("%")
mt["target_margin_%"] = pd.to_numeric(col.str.replace("%", "", regex=False),errors="coerce")
mt.loc[~is_percent, "target_margin_%"] *= 100

TypeError: bad operand type for unary ~: 'float'

In [ ]:
mt["target_margin_%"].isna()
margin_mean=mt["target_margin_%"].mean()
mt["target_margin_%"]=mt["target_margin_%"].fillna(margin_mean)
mt["target_margin_%"].isna().sum()

np.int64(0)

In [ ]:
mt["sales_target"] = (
    mt["sales_target"]
    .astype(str)
    .str.strip()
    .str.replace("$", "", regex=False)
    .str.replace("USD", "", regex=False)
    .str.strip()
)

mt["sales_target"] = pd.to_numeric(mt["sales_target"], errors="coerce")

In [ ]:
mt["sales_target"]=mt["sales_target"].fillna(mt["sales_target"].mean())

In [ ]:
mt["sales_target"].isna().sum()

np.int64(0)

In [ ]:
mt = mt.replace(
    r"(?i)^(unknown|missing|n/a|none)$",
    np.nan,
    regex=True
)

In [ ]:
mt.shape

(1905, 5)

In [ ]:
mt.head(2015)

          month         region     category  sales_target  target_margin_%
0    2022-01-01          north  electronics     204602.07        30.500000
1    2022-01-01          north         home     150116.61        21.897378
2    2022-01-01          north      fashion     216937.84        12.900000
3    2022-01-01          north       sports      77343.39        14.000000
4    2022-01-01          north       beauty      38576.45        11.600000
...         ...            ...          ...           ...              ...
2011 2025-06-01  international       sports     132161.84        14.000000
2012 2025-06-01  international       beauty     147307.44        29.100000
2013 2025-06-01  international      grocery     192465.69        27.700000
2014 2025-06-01  international       office      72763.56        29.600000
2015 2025-06-01  international          pet     238982.64        18.400000

[1905 rows x 5 columns]

In [ ]:
mt.isna().sum()

month              0
region             0
category           0
sales_target       0
target_margin_%    0
dtype: int64

In [ ]:
mt["region"].unique()
mt["category"].unique()

array(['electronics', 'home', 'fashion', 'sports', 'beauty', 'grocery',
       'pet', 'office'], dtype=object)

In [ ]:
mt["sales_target"].describe()

count      1905.00000
mean     138663.82746
std       65818.24663
min     -244279.23000
25%       93363.01000
50%      138663.82746
75%      188731.26000
max      249993.81000
Name: sales_target, dtype: float64

In [ ]:
mt.duplicated().sum()

np.int64(0)

In [ ]:
# Flag
mt["invalid_sales_flag"] = mt["sales_target"] < 0

# Remove invalid rows
mt = mt[mt["sales_target"] >= 0]

In [ ]:
mt.info()
mt.shape
mt.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1887 entries, 0 to 2015
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   month               1887 non-null   datetime64[ns]
 1   region              1887 non-null   object
 2   category            1887 non-null   object
 3   sales_target        1887 non-null   float64
 4   target_margin_%     1887 non-null   float64
 5   invalid_sales_flag  1887 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(2)
memory usage: 90.3+ KB

                               month   sales_target  target_margin_%
count                           1887    1887.000000      1887.000000
mean   2023-09-15 06:11:38.251192320  141370.867393        21.894333
min              2022-01-01 00:00:00   30006.670000         8.000000
25%              2022-11-01 00:00:00   94513.370000        15.600000
50%              2023-09-01 00:00:00  138663.827460        21.897378
75%              2024-08-01 00:00:00  189425.570000        28.400000
max              2025-06-01 00:00:00  249993.810000        35.000000
std                              NaN   59680.498877         7.581261

In [ ]:
mt["region"] = mt["region"].astype("category")
mt["category"] = mt["category"].astype("category")

C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\1872179320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mt["region"] = mt["region"].astype("category")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\1872179320.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mt["category"] = mt["category"].astype("category")

In [ ]:
mt.describe(include="all")

,month,region,category,sales_target,target_margin_%
count,1887,1887,1887,1887.000000,1887.000000
unique,NaN,6,8,NaN,NaN
top,NaN,east,grocery,NaN,NaN
freq,NaN,319,242,NaN,NaN
mean,2023-09-15 06:11:38.251192320,NaN,NaN,141370.867393,21.894333
min,2022-01-01 00:00:00,NaN,NaN,30006.670000,8.000000
25%,2022-11-01 00:00:00,NaN,NaN,94513.370000,15.600000
50%,2023-09-01 00:00:00,NaN,NaN,138663.827460,21.897378
75%,2024-08-01 00:00:00,NaN,NaN,189425.570000,28.400000
max,2025-06-01 00:00:00,NaN,NaN,249993.810000,35.000000
std,NaN,NaN,NaN,59680.498877,7.581261

In [ ]:
mt = mt.drop(columns=["invalid_sales_flag"])

### CLEANING OF products_dirty.csv

In [356]:
item=pd.read_csv("products_dirty.csv")

### function to remove the dirty  or missing values other than nan from whole data frame.

In [357]:
def remove_missing_values(df):
        df=df.replace([r"(?i)^\s*(unknown|missing|null|none|n/a)|\?\s*$"], np.nan, regex=True)
        return df
#regex=True allows Pandas to interpret the pattern as a regular expression, enabling flexible matching instead of exact string replacement.

### function for strandardizing the column names

In [358]:
def standardize_col_names(df):
    df.columns=(
            df.columns
            .str.lower()
            .str.strip()
            .str.replace(" ","_"))
    return df

In [359]:
item=standardize_col_names(item)
item.columns

Index(['product_id', 'sku', 'category', 'sub_category', 'product_name',
       'brand', 'list_price', 'standard_cost', 'product_status',
       'supplier_name', 'launch_date'],
      dtype='object')

### if 60 percent of data is missing in column better to drop

In [360]:
def threshhold(df):
    thresh=0.60*len(df)
    columns_to_drop=df.columns[df.isna().sum()>threshhold]
    df = df.drop(columns= columns_to_drop)
    return df

### drop the duplicate columns

In [361]:
def drop_duplicate_columns(df):
    df=df.loc[: , ~df.columns.duplicated()]
    return df

In [362]:
item=drop_duplicate_columns(item)
item.shape

(345, 11)

In [363]:
def drop_duplicate_rows(df):
    df=df.drop_duplicates()
    return df

In [364]:
item=drop_duplicate_rows(item)
item.shape

(345, 11)

### if i want to replace the numerical columns missing values then  calculate the mean of of non negative values and fill in the missing columns

In [365]:
# for numerical columns
def replace_missing_with_mean(df):
    for col in df.select_dtypes(include="number").columns:
        mean_val=df.loc[df[col]>0, col].mean()
        df[col] = df[col].fillna(mean_val)
    df[col] = df[col].fillna(mean_val)

In [366]:
# for categorical columns use mode
def replace_with_mode(df):
    for col in df.select_dtypes(include="object").columns:
        if not df[col].mode().empty:
            mode_val = df[col].mode()[0]
            df[col] = df[col].fillna(mode_val)
    return df

In [367]:
item=replace_with_mode(item)
item["product_name"].isna().sum()
item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      345 non-null    object
 1   sku             345 non-null    object
 2   category        345 non-null    object
 3   sub_category    345 non-null    object
 4   product_name    345 non-null    object
 5   brand           345 non-null    object
 6   list_price      345 non-null    object
 7   standard_cost   345 non-null    object
 8   product_status  345 non-null    object
 9   supplier_name   345 non-null    object
 10  launch_date     345 non-null    object
dtypes: object(11)
memory usage: 29.8+ KB

### strandardize the textual values

In [369]:
def strandardize_text_data(df):
    for col in df.select_dtypes(include="object").columns:
        df[col]=(df[col]
                .str.strip()
                .str.lower()
                )
    return df

In [370]:
item=strandardize_text_data(item)
item

,product_id,sku,category,sub_category,product_name,brand,list_price,standard_cost,product_status,supplier_name,launch_date
0,p00001,sku00001,electronics,phones,luma nova x 1,luma,564.94,466.28,active,delta goods,2024-07-12
1,p00002,sku00002,electronics,phones,apex nova x 2,apex,1099.33,713.83,seasonal,alpha supply,2023-10-26 00:00:00
2,p00003,sku00003,electronics,phones,everly nova x 3,everly,238.25,101.97,active,,03/28/2021
3,p00004,sku00004,electronics,phones,orbit pixelgo 1,orbit,usd 91.84,usd 71.92,active,alpha supply,07-jul-2024
4,p00005,sku00005,electronics,shoes,sierra pixelgo 2,sierra,903.67,636.22,active,beta wholesale,2021-02-19 00:00:00
5,p00006,sku00006,electronics,phones,luma pixelgo 3,nimbus,35.77,29.87,seasonal,alpha supply,2023-11-19
6,p00007,sku00007,electronics,phones,zenith imax mini 1,zenith,1249.5,569.98,seasonal,delta goods,"sep 22, 2024"
7,p00008,sku00008,electronics,phones,nimbus imax mini 2,nimbus,276.83,error,seasonal,delta goods,18-mar-2022
8,p00009,sku00009,electronics,phones,blueriver imax mini 3,blueriver,459.84,281.6,active,delta goods,06.10.2023
9,p00010,sku00010,electronics,phones,apex zenphone pro 1,apex,650.76,322.53,active,nova source,
10,p00011,sku00011,electronics,phones,orbit zenphone pro 2,orbit,919.72,386.05,active,gamma imports,28.02.2022
11,p00012,sku00012,electronics,phones,northstar zenphone pro 3,northstar,441.76,$235.54,seasonal,gamma imports,27-may-2024
12,p00013,sku00013,electronics,phones,apex talkone 1,apex,$686.82,usd 510.02,seasonal,delta goods,2024/03/17 00:00
13,p00014,sku00014,electronics,phones,orbit talkone 2,orbit,303.51,184.27,seasonal,nova source,"sep 27, 2024"
14,p00015,sku00015,electronics,phones,luma talkone 3,luma,,332.42,seasonal,prime traders,30/10/2022
15,p00016,sku00016,electronics,laptops,northstar notebook air 1,northstar,913.28,usd 397.52,discontinued,prime traders,06/29/2022
16,p00017,sku00017,electronics,laptops,orbit notebook air 2,orbit,102.25,84.30,discontinued,delta goods,06/11/2022
17,p00018,sku00018,electronics,laptops,trueline notebook air 3,trueline,1448.62,"1,092.55",discontinued,delta goods,2021-01-06
18,p00019,sku00019,electronics,laptops,pulse powerlap 14 1,pulse,usd 460.40,usd 183.62,active,gamma imports,2024/07/09 00:00
19,p00020,sku00020,electronics,laptops,pulse powerlap 14 2,pulse,1027.93,586.0,active,gamma imports,09/02/2021
20,p00021,sku00021,electronics,laptops,sierra powerlap 14 3,sierra,187.45,112.02,discontinued,gamma imports,20/11/2023
21,p00022,sku00022,electronics,laptops,primeco ultrabook x 1,primeco,usd 56.41,45.39,discontinued,prime traders,"mar 08, 2024"
22,p00023,sku00023,electronics,laptops,vertex ultrabook x 2,vertex,391.88,266.97,active,beta wholesale,31-jul-2022
23,p00024,sku00024,electronics,laptops,pulse ultrabook x 3,pulse,$471.01,287.33,discontinued,nova source,
24,p00025,sku00025,electronics,laptops,nimbus workmate 1,nimbus,822.33,363.82,active,prime traders,28/08/2022
25,p00026,sku00026,electronics,laptops,blueriver workmate 2,blueriver,1454.53,1072.81,active,nova source,"mar 03, 2021"
26,p00027,sku00027,electronics,laptops,primeco workmate 3,primeco,1409.55,1123.99,discontinued,prime traders,2023/12/29 00:00
27,p00028,sku00028,electronics,laptops,trueline gamecore 1,trueline,898.86,728.92,discontinued,beta wholesale,2024/07/07 00:00
28,p00029,sku00029,electronics,laptops,pulse gamecore 2,pulse,137.3,61.51,active,prime traders,2021-04-01 00:00:00
29,p00030,sku00030,electronics,laptops,sierra gamecore 3,sierra,72.61,37.22,discontinued,nova source,09.02.2022
30,p00031,sku00031,electronics,audio,northstar basspods 1,northstar,586.07,284.64,active,alpha supply,2021/02/02 00:00
31,p00032,sku00032,electronics,audio,zenith basspods 2,zenith,1243.96,657.28,discontinued,beta wholesale,2021/11/23 00:00
32,p00033,sku00033,electronics,audio,nimbus basspods 3,nimbus,425.0,264.07,seasonal,nova source,not a date
33,p00034,sku00034,electronics,audio,everly soundmax 1,everly,215.68,162.00,seasonal,gamma imports,2024/08/13 00:00
34,,sku00035,electronics,audio,blueriver workmate 2,trueline,116.45,98.22,discontinued,delta goods,2022-10-31
35,p00036,sku00036,electronics,audio,trueline soundmax 3,trueline,$1159.51,521.03,active,delta goods,"may 06, 2021"
36,p00037,sku00037,electronics,audio,sierra echobuds 1,sierra,13.26,10.05,active,alpha supply,2023-03-29 00:00:00
37,p00038,sku00038,electronics,audio,apex echobuds 2,apex,?,usd 758.62,seasonal,prime traders,08-dec-2020
38,p00039,sku00039,electronics,audio,orbit echobuds 3,orbit,1158.05,448.19,discontinued,,20/12/2020
39,p00040,sku00040,electronics,audio,nimbus wavebeat 1,nimbus,540.91,220.66,active,gamma imports,2020-10-28
40,p00041,sku00041,electronics,audio,vivid wavebeat 2,vivid,$1295.34,857.06,active,prime traders,"aug 17, 2024"
41,p00042,sku00042,electronics,audio,blueriver wavebeat 3,blueriver,499.69,190.77,discontinued,gamma imports,22/09/2021
42,p00043,,electronics,audio,urbanpeak quiettune 1,urbanpeak,usd 469.92,$240.88,seasonal,gamma imports,06-nov-2022
43,p00044,sku00044,electronics,audio,vivid quiettune 2,vivid,1095.76,732.82,discontinued,alpha supply,2022-05-27 00:00:00
44,p00045,sku00045,electronics,audio,blueriver workmate 2,vertex,1331.38,780.33,discontinued,beta wholesale,05/04/2020
45,p00046,sku00046,electronics,accessories,primeco chargepro 1,nimbus,183.79,129.87,active,alpha supply,24.12.2021
46,p00047,sku00047,electronics,accessories,luma chargepro 2,luma,$1142.37,720.42,discontinued,alpha supply,"nov 03, 2021"
47,p00048,sku00048,electronics,accessories,sierra chargepro 3,sierra,1157.60,690.97,seasonal,gamma imports,02.06.2020
48,p00049,sku00049,electronics,accessories,luma wirehub 1,luma,786.49,$443.40,active,prime traders,"feb 07, 2022"
49,p00050,,electronics,accessories,trueline wirehub 2,trueline,43.0,17.37,seasonal,alpha supply,2021-04-30
50,po0051,sku00051,electronics,accessories,vertex wirehub 3,vertex,51.99,34.74,seasonal,alpha supply,2023-02-07 00:00:00
51,p00052,sku00052,electronics,accessories,sierra flexcase 1,sierra,474.96,287.01,active,prime traders,18.05.2020
52,,unknown,electronics,accessories,vertex flexcase 2,vertex,1361.81,usd 646.38,discontinued,nova source,30/03/2022
53,p00054,sku00054,electronics,accessories,blueriver flexcase 3,blueriver,618.52,450.14,discontinued,gamma imports,2024/05/12 00:00
54,p00055,sku00055,electronics,accessories,zenith screenguard 1,zenith,347.05,$134.83,seasonal,beta wholesale,2022-05-21 00:00:00
55,p00056,sku00056,electronics,accessories,sierra screenguard 2,sierra,438.18,usd 188.68,seasonal,delta goods,18/12/2023
56,p00057,sku00057,electronics,accessories,orbit screenguard 3,orbit,"1,394.90",$1051.84,seasonal,prime traders,"aug 02, 2024"
57,p00058,sku00058,electronics,accessories,primeco traveldock 1,primeco,951.94,747.97,active,nova source,27/09/2022
58,p00059,sku00059,electronics,accessories,orbit traveldock 2,orbit,1206.49,534.82,active,nova source,"jul 26, 2024"
59,p00060,sku00060,electronics,accessories,pulse traveldock 3,pulse,1339.38,829.98,discontinued,nova source,
60,p00061,sku00061,home,kitchen,blueriver blendmaster 1,blueriver,1212.12,usd 967.33,discontinued,nova source,2021-08-26 00:00:00
61,p00062,sku00062,home,kitchen,nimbus blendmaster 2,nimbus,480.42,194.58,active,beta wholesale,29.10.2021
62,p00063,sku00063,home,kitchen,zenith blendmaster 3,zenith,345.76,194.85,seasonal,beta wholesale,2022-11-16 00:00:00
63,po0064,sku00064,home,shoes,zenith quickkettle 1,zenith,1227.93,958.23,seasonal,alpha supply,05.03.2023
64,p00065,sku00065,home,kitchen,primeco quickkettle 2,primeco,15.39,9.32,active,prime traders,05/16/2024 pst
65,p00066,sku00066,home,kitchen,luma quickkettle 3,luma,629.03,290.02,discontinued,delta goods,02/05/2020
66,p00067,sku00067,home,kitchen,blueriver chefpan 1,blueriver,184.2,95.56,seasonal,nova source,
67,po0068,sku00068,home,kitchen,urbanpeak chefpan 2,urbanpeak,1414.65,723.74,active,gamma imports,2021-06-05 00:00:00
68,p00069,sku00069,home,kitchen,everly chefpan 3,everly,780.59,547.59,active,gamma imports,2022-12-22 00:00:00z
69,p00070,sku00070,home,kitchen,orbit freshbox 1,orbit,548.63,458.59,seasonal,gamma imports,30.08.2024
70,p00071,sku00071,home,kitchen,northstar freshbox 2,northstar,1443.86,error,seasonal,delta goods,27/02/2022
71,p00072,sku00072,home,kitchen,everly freshbox 3,everly,$748.39,374.52,seasonal,delta goods,2021-07-25
72,p00073,sku00073,home,kitchen,trueline toastup 1,trueline,430.84,158.74,discontinued,alpha supply,06/22/2022
73,p00074,sku00074,home,kitchen,zenith toastup 2,zenith,916.30,usd 551.01,seasonal,delta goods,15/07/2021
74,p00075,sku00075,home,kitchen,blueriver toastup 3,blueriver,81.96,40.1,discontinued,beta wholesale,05.08.2020
75,p00076,sku00076,home,furniture,orbit oakdesk 1,orbit,-1362.86,640.25,active,gamma imports,08-feb-2022
76,p00077,sku00077,home,furniture,northstar oakdesk 2,northstar,221.62,131.8,discontinued,prime traders,01/11/2022
77,p00078,sku00078,home,furniture,nimbus oakdesk 3,nimbus,1478.55,696.44,active,beta wholesale,11/05/2021
78,p00079,sku00079,home,furniture,vivid cloudchair 1,vivid,1009.84,738.0,active,nova source,2021-07-25 00:00:00
79,p00080,sku00080,home,furniture,vertex cloudchair 2,vertex,,257.27,seasonal,nova source,2022-04-04 00:00:00
80,p00081,sku00081,home,furniture,vertex cloudchair 3,vertex,554.84,369.61,seasonal,gamma imports,2024-04-26
81,p00082,sku00082,home,furniture,blueriver flexshelf 1,blueriver,952.13,588.31,seasonal,prime traders,2021/05/06 00:00
82,p00083,sku00083,home,furniture,nimbus flexshelf 2,nimbus,139.98,107.46,discontinued,prime traders,12-dec-2020
83,p00084,sku00084,home,furniture,blueriver flexshelf 3,blueriver,484.57,$214.79,seasonal,gamma imports,05-may-2020
84,p00085,sku00085,home,furniture,urbanpeak comfysofa 1,urbanpeak,65.96,42.57,seasonal,nova source,08.01.2024
85,p00086,sku00086,home,furniture,everly comfysofa 2,everly,$1017.96,364.73,seasonal,nova source,2023-03-09 00:00:00
86,p00087,sku00087,home,furniture,vivid comfysofa 3,vivid,770.58,356.97,active,delta goods,2024/08/22 00:00
87,p00088,sku00088,home,furniture,luma nightstand 1,,969.53,423.86,seasonal,gamma imports,22/09/2023
88,p00089,sku00089,home,furniture,nimbus nightstand 2,nimbus,1037.95,563.99,seasonal,alpha supply,01/30/2024
89,p00090,sku00090,home,furniture,zenith nightstand 3,zenith,usd 1405.41,-588.53,seasonal,alpha supply,2022-03-31 00:00:00
90,po0091,sku00091,home,decor,pulse glowlamp 1,pulse,514.89,?,discontinued,prime traders,2024-05-29
91,p00092,sku00092,home,decor,pulse glowlamp 2,pulse,1387.42,1094.22,seasonal,beta wholesale,2021-12-26 00:00:00
92,p00093,sku00093,home,decor,primeco glowlamp 3,?,390.62,265.62,active,beta wholesale,2023/07/18 00:00
93,p00094,skuo0094,home,decor,everly wallart 1,everly,1226.75,$769.91,discontinued,delta goods,2021/01/24 00:00
94,p00095,sku00095,home,decor,vertex wallart 2,vertex,,375.25,discontinued,delta goods,2022-11-08
95,p00096,sku00096,home,decor,apex wallart 3,apex,144.19,usd 115.15,seasonal,beta wholesale,03-sep-2023z
96,p00097,sku00097,home,decor,zenith softrug 1,zenith,-1351.12,900.59,seasonal,gamma imports,09/04/2024
97,p00098,sku00098,home,decor,everly softrug 2,everly,511.85,268.52,seasonal,beta wholesale,07/22/2024
98,p00099,sku00099,home,decor,pulse softrug 3,pulse,1090.30,870.66,active,gamma imports,2020/04/19 00:00
99,p00100,sku00100,home,decor,northstar aromadiffuser 1,northstar,usd 1331.19,985.00,active,alpha supply,2022-08-22
100,p00101,sku00101,home,decor,vivid aromadiffuser 2,vivid,964.84,378.28,seasonal,alpha supply,2023/01/15 00:00
101,p00102,sku00102,home,decor,everly aromadiffuser 3,everly,usd 246.63,197.13,seasonal,alpha supply,05/22/2020
102,p00103,sku00103,home,decor,northstar mirrorlite 1,northstar,911.61,323.26,seasonal,delta goods,28-feb-2021
103,p00104,sku00104,home,decor,orbit mirrorlite 2,orbit,156.7,unknown,active,alpha supply,2022/08/10 00:00
104,p00105,sku00105,home,decor,primeco mirrorlite 3,primeco,12.57,5.41,active,alpha supply,16.09.2024
105,p00106,sku00106,fashion,men,northstar urban tee 1,northstar,825.36,574.41,seasonal,prime traders,05.10.2024
106,p00107,sku00107,fashion,men,zenith urban tee 2,zenith,usd 979.68,452.74,active,beta wholesale,12/07/2020
107,p00108,skuo0108,fashion,men,trueline urban tee 3,trueline,1069.71,501.29,discontinued,delta goods,16/01/2022
108,p00109,sku00109,fashion,men,urbanpeak classic shirt 1,urbanpeak,491.47,?,active,delta goods,24.06.2022
109,p00110,sku00110,fashion,men,nimbus classic shirt 2,nimbus,976.2,756.18,discontinued,gamma imports,04/27/2022
110,p00111,sku00111,fashion,men,zenith classic shirt 3,zenith,988.13,626.63,discontinued,prime traders,2020/03/08 00:00
111,p00112,sku00112,fashion,men,orbit denim flex 1,orbit,145.04,error,active,beta wholesale,2020/04/15 00:00
112,p00113,sku00113,fashion,men,orbit denim flex 2,orbit,401.48,189.50,seasonal,gamma imports,2020-09-18 00:00:00
113,p00114,sku00114,fashion,men,nimbus denim flex 3,nimbus,1459.65,797.77,active,gamma imports,11/21/2024
114,p00115,sku00115,fashion,men,sierra runner jacket 1,sierra,1338.61,890.94,discontinued,alpha supply,07/03/2024
115,p00116,sku00116,fashion,men,vivid runner jacket 2,vivid,1193.24,717.52,active,prime traders,15/01/2020
116,p00117,sku00117,fashion,men,pulse runner jacket 3,pulse,867.47,517.24,seasonal,prime traders,2023-10-08 utc
117,p00118,sku00118,fashion,men,pulse polo edge 1,pulse,296.89,211.16,active,nova source,2023/12/28 00:00
118,p00119,sku00119,fashion,men,vertex polo edge 2,vertex,424.75,usd 153.83,seasonal,beta wholesale,24.12.2021
119,p00120,sku00120,fashion,men,urbanpeak polo edge 3,urbanpeak,969.98,425.39,seasonal,gamma imports,19.04.2021
120,p00121,sku00121,fashion,women,vertex silktop 1,vertex,"1,410.99",1166.84,discontinued,delta goods,2024-03-08 00:00:00
121,p00122,sku00122,fashion,women,northstar silktop 2,northstar,?,734.51,seasonal,beta wholesale,2024/05/11 00:00
122,p00123,sku00123,fashion,women,blueriver silktop 3,blueriver,28.11,$22.89,active,beta wholesale,"may 07, 2023"
123,p00124,sku00124,fashion,women,zenith daily dress 1,zenith,645.14,537.61,seasonal,delta goods,
124,p00125,sku00125,fashion,women,pulse daily dress 2,pulse,1445.61,1122.52,seasonal,nova source,2022-06-18
125,p00126,sku00126,fashion,women,sierra daily dress 3,sierra,445.2,241.54,active,nova source,2022-10-01 00:00:00
126,p00127,sku00127,fashion,women,sierra comfy jeans 1,sierra,1277.45,?,discontinued,prime traders,21.02.2022
127,p00128,sku00128,fashion,women,blueriver comfy jeans 2,blueriver,258.39,162.37,seasonal,nova source,24/07/2020
128,p00129,sku00129,fashion,women,luma comfy jeans 3,luma,1404.55,980.40,discontinued,gamma imports,2024/02/02 00:00
129,p00130,sku00130,fashion,women,urbanpeak active leggings 1,urbanpeak,857.24,341.69,seasonal,alpha supply,2021/02/27 00:00
130,p00131,sku00131,fashion,women,urbanpeak active leggings 2,urbanpeak,924.44,usd 781.18,active,nova source,2023-02-11
131,,sku00132,fashion,women,orbit active leggings 3,orbit,214.43,?,active,nova source,
132,p00133,sku00133,fashion,women,blueriver workmate 2,nimbus,1316.67,usd 948.51,discontinued,alpha supply,16-mar-2021
133,p00134,sku00134,fashion,women,apex bliss scarf 2,apex,1047.04,734.23,seasonal,nova source,2022-04-22 00:00:00
134,p00135,sku00135,fashion,women,northstar bliss scarf 3,northstar,usd 542.44,$269.48,active,nova source,2020-10-16 00:00:00
135,p00136,sku00136,fashion,shoes,trueline stride one 1,trueline,"1,214.99",917.39,active,delta goods,2024-04-12
136,p00137,sku00137,fashion,shoes,blueriver workmate 2,apex,1301.27,"1,049.63",active,prime traders,2024-06-25
137,p00138,sku00138,fashion,shoes,sierra stride one 3,sierra,769.46,-462.26,seasonal,beta wholesale,04-mar-2020 pst
138,p00139,sku00139,fashion,shoes,apex citywalk 1,apex,1198.45,808.93,active,nova source,27-oct-2021
139,p00140,sku00140,fashion,shoes,nimbus citywalk 2,nimbus,1054.44,788.61,active,alpha supply,28/06/2023
140,p00141,sku00141,fashion,shoes,vivid citywalk 3,vivid,1335.56,693.15,discontinued,beta wholesale,2023-01-04
141,p00142,sku00142,fashion,shoes,nimbus trailx 1,nimbus,566.5,usd 224.90,seasonal,alpha supply,13-aug-2023
142,p00143,sku00143,fashion,shoes,orbit trailx 2,orbit,-869.53,,discontinued,beta wholesale,29-dec-2023
143,p00144,sku00144,fashion,shoes,luma trailx 3,luma,701.07,435.59,discontinued,beta wholesale,2024/01/21 00:00
144,p00145,sku00145,fashion,shoes,orbit airmove 1,orbit,$433.38,279.71,seasonal,alpha supply,06/04/2024
145,p00146,sku00146,fashion,shoes,vertex airmove 2,vertex,50.6,18.65,,gamma imports,14-oct-2021
146,p00147,sku00147,fashion,shoes,zenith airmove 3,zenith,1234.79,654.56,seasonal,beta wholesale,07/10/2022
147,p00148,sku00148,fashion,shoes,trueline classic loafer 1,trueline,194.96,119.14,discontinued,beta wholesale,2022-01-20 00:00:00
148,p00149,sku00149,fashion,shoes,orbit classic loafer 2,orbit,"1,156.14",529.41,discontinued,nova source,23.04.2023
149,p00150,sku00150,fashion,shoes,pulse classic loafer 3,pulse,936.22,367.63,discontinued,beta wholesale,07/21/2022
150,p00151,sku00151,sports,fitness,orbit yogamat 1,orbit,82.26,$50.65,active,nova source,2020-11-28
151,p00152,sku00152,sports,fitness,nimbus yogamat 2,nimbus,usd 813.25,543.83,seasonal,alpha supply,2020-04-17 00:00:00
152,p00153,sku00153,sports,fitness,blueriver yogamat 3,blueriver,usd 1090.51,913.77,discontinued,gamma imports,21/10/2023
153,p00154,sku00154,sports,fitness,blueriver powerbands 1,blueriver,776.87,397.35,discontinued,gamma imports,2022-05-30 00:00:00
154,p00155,sku00155,sports,fitness,urbanpeak powerbands 2,urbanpeak,1193.8,579.49,seasonal,prime traders,12-aug-2020
155,p00156,sku00156,sports,fitness,apex powerbands 3,apex,661.26,257.38,seasonal,alpha supply,2020/10/20 00:00
156,p00157,sku00157,sports,fitness,luma smartbottle 1,luma,zero,$35.66,seasonal,beta wholesale,30.03.2022
157,p00158,sku00158,sports,fitness,nimbus smartbottle 2,nimbus,usd 1254.79,875.83,active,prime traders,2022/09/05 00:00
158,p00159,sku00159,sports,fitness,blueriver smartbottle 3,blueriver,usd 616.38,?,seasonal,prime traders,"feb 24, 2021"
159,p00160,sku00160,sports,fitness,primeco coreball 1,primeco,$238.87,113.49,active,nova source,04/02/2023
160,p00161,sku00161,sports,fitness,orbit coreball 2,orbit,826.09,$584.29,active,prime traders,30-mar-2022
161,p00162,sku00162,sports,fitness,orbit coreball 3,orbit,992.0,486.05,seasonal,nova source,2022-12-20
162,p00163,sku00163,sports,fitness,urbanpeak jumppro 1,urbanpeak,1432.52,1029.91,active,prime traders,2020-07-25
163,p00164,sku00164,sports,fitness,blueriver jumppro 2,blueriver,833.76,$546.83,active,alpha supply,2021/12/31 00:00
164,p00165,sku00165,sports,fitness,everly jumppro 3,everly,632.3,299.63,discontinued,alpha supply,2022-07-14 00:00:00
165,p00166,sku00166,sports,outdoor,orbit camplite 1,orbit,$537.18,391.56,active,prime traders,"may 09, 2022"
166,p00167,sku00167,sports,outdoor,urbanpeak camplite 2,urbanpeak,26.52,usd 10.82,seasonal,gamma imports,05/28/2024
167,p00168,sku00168,sports,outdoor,nimbus camplite 3,nimbus,$73.77,27.32,active,alpha supply,27/02/2022
168,po0169,sku00169,sports,outdoor,luma trailbag 1,luma,1283.91,901.09,seasonal,delta goods,"jul 28, 2023"
169,p00170,sku00170,sports,outdoor,vivid trailbag 2,vivid,713.89,usd 284.78,active,gamma imports,"oct 03, 2024"
170,p00171,sku00171,sports,outdoor,nimbus trailbag 3,nimbus,739.97,434.17,active,alpha supply,2024-05-03
171,p00172,sku00172,sports,outdoor,vertex hikepole 1,vertex,263.94,usd 149.63,discontinued,delta goods,"jul 24, 2022"
172,p00173,sku00173,sports,outdoor,urbanpeak hikepole 2,urbanpeak,600.76,395.26,discontinued,prime traders,12/05/2023
173,p00174,sku00174,sports,outdoor,orbit hikepole 3,orbit,954.47,unknown,discontinued,gamma imports,27.06.2022
174,p00175,sku00175,sports,outdoor,zenith suntent 1,zenith,usd 565.05,374.59,active,prime traders,2020/11/15 00:00
175,p00176,sku00176,sports,outdoor,vertex suntent 2,vertex,usd 757.19,589.28,discontinued,beta wholesale,01/30/2023

Compare Mean & Median
Case	Interpretation
mean > median	right skew(more of small values)
mean < median	left skew(more of large values)
mean ≈ median	normal

### Function calls

In [371]:
product=remove_missing_values(item)

In [372]:
pd.set_option("display.max_rows", 400)

Now checking the column wise data

In [373]:
item.columns

Index(['product_id', 'sku', 'category', 'sub_category', 'product_name',
       'brand', 'list_price', 'standard_cost', 'product_status',
       'supplier_name', 'launch_date'],
      dtype='object')

In [374]:
item["product_id"] = item["product_id"].replace(r"^\s*$", np.nan, regex=True)
item = item.dropna(subset=["product_id"])
item["product_id"]
item["product_id"]=(
    item["product_id"]
    .str.strip()
    .str.upper()
    .str.replace("O", "0", regex=False)
)
item["product_id"]

C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\4155098398.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  item["product_id"]=(

0      P00001
1      P00002
2      P00003
3      P00004
4      P00005
5      P00006
6      P00007
7      P00008
8      P00009
9      P00010
10     P00011
11     P00012
12     P00013
13     P00014
14     P00015
15     P00016
16     P00017
17     P00018
18     P00019
19     P00020
20     P00021
21     P00022
22     P00023
23     P00024
24     P00025
25     P00026
26     P00027
27     P00028
28     P00029
29     P00030
30     P00031
31     P00032
32     P00033
33     P00034
35     P00036
36     P00037
37     P00038
38     P00039
39     P00040
40     P00041
41     P00042
42     P00043
43     P00044
44     P00045
45     P00046
46     P00047
47     P00048
48     P00049
49     P00050
50     P00051
51     P00052
53     P00054
54     P00055
55     P00056
56     P00057
57     P00058
58     P00059
59     P00060
60     P00061
61     P00062
62     P00063
63     P00064
64     P00065
65     P00066
66     P00067
67     P00068
68     P00069
69     P00070
70     P00071
71     P00072
72     P00073
73     P00074
74     P00075
75     P00076
76     P00077
77     P00078
78     P00079
79     P00080
80     P00081
81     P00082
82     P00083
83     P00084
84     P00085
85     P00086
86     P00087
87     P00088
88     P00089
89     P00090
90     P00091
91     P00092
92     P00093
93     P00094
94     P00095
95     P00096
96     P00097
97     P00098
98     P00099
99     P00100
100    P00101
101    P00102
102    P00103
103    P00104
104    P00105
105    P00106
106    P00107
107    P00108
108    P00109
109    P00110
110    P00111
111    P00112
112    P00113
113    P00114
114    P00115
115    P00116
116    P00117
117    P00118
118    P00119
119    P00120
120    P00121
121    P00122
122    P00123
123    P00124
124    P00125
125    P00126
126    P00127
127    P00128
128    P00129
129    P00130
130    P00131
132    P00133
133    P00134
134    P00135
135    P00136
136    P00137
137    P00138
138    P00139
139    P00140
140    P00141
141    P00142
142    P00143
143    P00144
144    P00145
145    P00146
146    P00147
147    P00148
148    P00149
149    P00150
150    P00151
151    P00152
152    P00153
153    P00154
154    P00155
155    P00156
156    P00157
157    P00158
158    P00159
159    P00160
160    P00161
161    P00162
162    P00163
163    P00164
164    P00165
165    P00166
166    P00167
167    P00168
168    P00169
169    P00170
170    P00171
171    P00172
172    P00173
173    P00174
174    P00175
175    P00176
176    P00177
177    P00178
178    P00179
179    P00180
180    P00181
181    P00182
182    P00183
183    P00184
184    P00185
185    P00186
186    P00187
187    P00188
188    P00189
189    P00190
190    P00191
191    P00192
192    P00193
193    P00194
194    P00195
195    P00196
196    P00197
197    P00198
198    P00199
199    P00200
200    P00201
201    P00202
202    P00203
203    P00204
204    P00205
205    P00206
206    P00207
207    P00208
208    P00209
209    P00210
210    P00211
211    P00212
212    P00213
213    P00214
214    P00215
215    P00216
216    P00217
217    P00218
218    P00219
219    P00220
220    P00221
221    P00222
222    P00223
223    P00224
224    P00225
225    P00226
226    P00227
227    P00228
229    P00230
230    P00231
231    P00232
232    P00233
233    P00234
234    P00235
235    P00236
236    P00237
237    P00238
238    P00239
239    P00240
240    P00241
241    P00242
242    P00243
243    P00244
244    P00245
245    P00246
246    P00247
247    P00248
248    P00249
249    P00250
250    P00251
251    P00252
252    P00253
253    P00254
254    P00255
255    P00256
256    P00257
257    P00258
258    P00259
259    P00260
260    P00261
261    P00262
262    P00263
263    P00264
264    P00265
265    P00266
266    P00267
267    P00268
268    P00269
269    P00270
270    P00271
271    P00272
272    P00273
273    P00274
274    P00275
275    P00276
276    P00277
277    P00278
278    P00279
279    P00280
280    P00281
281    P00282
282    P00283
283    P00284
284    P00285
285    P00286
286    P00287
287    P00288
288    P00289
289    P00290
290    P00291
291    P00292
292    P00293
293    P00294
294    P00295
295    P00296
296    P00297
297    P00298
298    P00299
299    P00300
300    P00301
301    P00302
302    P00303
303    P00304
304    P00305
305    P00306
306    P00307
307    P00308
308    P00309
309    P00310
310    P00311
311    P00312
312    P00313
313    P00314
314    P00315
315    P00316
316    P00317
318    P00319
319    P00320
320    P00321
321    P00322
322    P00323
323    P00324
324    P00325
325    P00326
326    P00327
327    P00328
328    P00329
329    P00330
330    P00331
331    P00332
332    P00333
333    P00334
334    P00335
335    P00336
336    P00337
337    P00338
338    P00339
339    P00340
340    P00341
341    P00342
342    P00343
343    P00344
344    P00345
Name: product_id, dtype: object

In [375]:
item["sku"]=(item["sku"]
            .str.strip()
            .str.upper()
            .str.replace("o","0"))
item["sku"]
#identify the missing values
item["sku"] = item["sku"].replace(r"^\s*$", np.nan, regex=True)
mask = item["sku"].isna()
item.loc[mask, "sku"] = "SKU" + (item.index[mask] + 1).astype(str).str.zfill(5)
item["sku"]

C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\2717229321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  item["sku"]=(item["sku"]
C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\2717229321.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  item["sku"] = item["sku"].replace(r"^\s*$", np.nan, regex=True)

0      SKU00001
1      SKU00002
2      SKU00003
3      SKU00004
4      SKU00005
5      SKU00006
6      SKU00007
7      SKU00008
8      SKU00009
9      SKU00010
10     SKU00011
11     SKU00012
12     SKU00013
13     SKU00014
14     SKU00015
15     SKU00016
16     SKU00017
17     SKU00018
18     SKU00019
19     SKU00020
20     SKU00021
21     SKU00022
22     SKU00023
23     SKU00024
24     SKU00025
25     SKU00026
26     SKU00027
27     SKU00028
28     SKU00029
29     SKU00030
30     SKU00031
31     SKU00032
32     SKU00033
33     SKU00034
35     SKU00036
36     SKU00037
37     SKU00038
38     SKU00039
39     SKU00040
40     SKU00041
41     SKU00042
42     SKU00043
43     SKU00044
44     SKU00045
45     SKU00046
46     SKU00047
47     SKU00048
48     SKU00049
49     SKU00050
50     SKU00051
51     SKU00052
53     SKU00054
54     SKU00055
55     SKU00056
56     SKU00057
57     SKU00058
58     SKU00059
59     SKU00060
60     SKU00061
61     SKU00062
62     SKU00063
63     SKU00064
64     SKU00065
65     SKU00066
66     SKU00067
67     SKU00068
68     SKU00069
69     SKU00070
70     SKU00071
71     SKU00072
72     SKU00073
73     SKU00074
74     SKU00075
75     SKU00076
76     SKU00077
77     SKU00078
78     SKU00079
79     SKU00080
80     SKU00081
81     SKU00082
82     SKU00083
83     SKU00084
84     SKU00085
85     SKU00086
86     SKU00087
87     SKU00088
88     SKU00089
89     SKU00090
90     SKU00091
91     SKU00092
92     SKU00093
93     SKUO0094
94     SKU00095
95     SKU00096
96     SKU00097
97     SKU00098
98     SKU00099
99     SKU00100
100    SKU00101
101    SKU00102
102    SKU00103
103    SKU00104
104    SKU00105
105    SKU00106
106    SKU00107
107    SKUO0108
108    SKU00109
109    SKU00110
110    SKU00111
111    SKU00112
112    SKU00113
113    SKU00114
114    SKU00115
115    SKU00116
116    SKU00117
117    SKU00118
118    SKU00119
119    SKU00120
120    SKU00121
121    SKU00122
122    SKU00123
123    SKU00124
124    SKU00125
125    SKU00126
126    SKU00127
127    SKU00128
128    SKU00129
129    SKU00130
130    SKU00131
132    SKU00133
133    SKU00134
134    SKU00135
135    SKU00136
136    SKU00137
137    SKU00138
138    SKU00139
139    SKU00140
140    SKU00141
141    SKU00142
142    SKU00143
143    SKU00144
144    SKU00145
145    SKU00146
146    SKU00147
147    SKU00148
148    SKU00149
149    SKU00150
150    SKU00151
151    SKU00152
152    SKU00153
153    SKU00154
154    SKU00155
155    SKU00156
156    SKU00157
157    SKU00158
158    SKU00159
159    SKU00160
160    SKU00161
161    SKU00162
162    SKU00163
163    SKU00164
164    SKU00165
165    SKU00166
166    SKU00167
167    SKU00168
168    SKU00169
169    SKU00170
170    SKU00171
171    SKU00172
172    SKU00173
173    SKU00174
174    SKU00175
175    SKU00176
176    SKU00177
177    SKU00178
178    SKUO0179
179    SKU00180
180    SKU00181
181    SKU00182
182    SKU00183
183    SKU00184
184    SKU00185
185    SKU00186
186    SKU00187
187    SKU00188
188    SKU00189
189    SKU00190
190    SKU00191
191    SKU00192
192    SKU00193
193    SKU00194
194    SKU00195
195    SKU00196
196    SKU00197
197    SKU00198
198    SKU00199
199    SKU00200
200    SKU00201
201    SKU00202
202    SKU00203
203    SKU00204
204    SKU00205
205    SKU00206
206    SKU00207
207    SKU00208
208    SKU00209
209    SKU00210
210    SKU00211
211    SKU00212
212    SKU00213
213    SKU00214
214    SKU00215
215    SKU00216
216    SKU00217
217    SKU00218
218    SKU00219
219    SKU00220
220    SKU00221
221    SKU00222
222    SKU00223
223    SKU00224
224    SKUO0225
225    SKU00226
226    SKU00227
227    SKU00228
229    SKU00230
230    SKU00231
231    SKU00232
232    SKU00233
233    SKU00234
234    SKU00235
235    SKU00236
236    SKU00237
237    SKU00238
238    SKU00239
239    SKU00240
240    SKU00241
241    SKU00242
242    SKU00243
243    SKU00244
244    SKU00245
245    SKU00246
246    SKU00247
247    SKUO0248
248    SKU00249
249    SKU00250
250    SKU00251
251    SKU00252
252    SKU00253
253    SKU00254
254    SKU00255
255    SKU00256
256    SKU00257
257    SKUO0258
258    SKU00259
259    SKU00260
260    SKUO0261
261    SKU00262
262    SKU00263
263    SKU00264
264    SKU00265
265    SKU00266
266    SKU00267
267    SKUO0268
268    SKU00269
269    SKU00270
270    SKU00271
271    SKU00272
272    SKU00273
273    SKU00274
274    SKU00275
275    SKU00276
276    SKU00277
277    SKU00278
278    SKU00279
279    SKU00280
280    SKU00281
281    SKU00282
282    SKU00283
283    SKU00284
284    SKU00285
285    SKU00286
286    SKU00287
287    SKU00288
288    SKU00289
289    SKU00290
290    SKU00291
291    SKU00292
292    SKU00293
293    SKU00294
294    SKU00295
295    SKU00296
296    SKU00297
297    SKU00298
298    SKU00299
299    SKU00300
300    SKU00301
301    SKU00302
302    SKU00303
303    SKU00304
304    SKU00305
305    SKU00306
306    SKU00307
307    SKU00308
308    SKU00309
309    SKU00310
310    SKU00311
311    SKU00312
312    SKU00313
313    SKU00314
314    SKU00315
315    SKU00316
316    SKU00317
318    SKU00319
319    SKU00320
320    SKU00321
321    SKU00322
322    SKU00323
323    SKU00324
324    SKU00325
325    SKU00326
326    SKU00327
327    SKU00328
328    SKU00329
329    SKU00330
330    SKU00331
331    SKU00332
332    SKU00333
333    SKU00334
334    SKU00335
335    SKU00336
336    SKU00337
337    SKU00338
338    SKU00339
339    SKU00340
340    SKU00341
341    SKU00342
342    SKU00343
343    SKU00344
344    SKU00345
Name: sku, dtype: object

In [376]:
item = item[item["sub_category"] != "missing"]
item["sub_category"].value_counts()

sub_category
shoes          18
laptops        15
furniture      15
outdoor        15
fitness        15
men            15
decor          15
cat            15
stationery     15
storage        15
snacks         15
skincare       15
cycling        15
beverages      15
phones         14
kitchen        14
accessories    14
audio          14
women          14
haircare       14
makeup         14
staples        14
dog            14
Name: count, dtype: int64

In [377]:
item["product_name"] = item["product_name"].replace(r"^\s*$", np.nan, regex=True)
item=item.dropna(subset="product_name")
item["product_name"].isna().sum()

np.int64(0)

In [378]:
item=remove_missing_values(item)
item["brand"].value_counts()
item["brand"] = item["brand"].replace(r"^\s*$", np.nan, regex=True)
item=item.dropna(subset="brand")
item["brand"].isna().sum()

np.int64(0)

In [379]:
item["product_status"].value_counts()
item["product_status"] = item["product_status"].replace(r"^\s*$", np.nan, regex=True)
item=item.dropna(subset="product_status")
item["product_status"].value_counts()

product_status
seasonal        115
active          113
discontinued    105
Name: count, dtype: int64

In [380]:
item["supplier_name"]
item["supplier_name"] = item["supplier_name"].replace(r"^\s*$", np.nan, regex=True)
item=item.dropna(subset="product_status")
item["supplier_name"].value_counts()
item["supplier_name"]=item["supplier_name"].replace("  "," ", regex=True)
item["supplier_name"].value_counts()

supplier_name
gamma imports     66
nova source       60
prime traders     55
alpha supply      53
beta wholesale    47
delta goods       46
Name: count, dtype: int64

In [ ]:
item["launch_date"]
item["launch_date"] = item["launch_date"].replace(r"^\s*$", np.nan, regex=True)
item["launch_date"] = item["launch_date"].replace([
    "not a date",
    "00/00/0000"
], np.nan)
item["launch_date"]= item["launch_date"].str.lower()
item["launch_date"] = item["launch_date"].str.replace(
    r"(pst|utc|z|\+\d{2}:\d{2})", "", regex=True
).str.strip()
item["launch_date"] = pd.to_datetime(
    item["launch_date"],
    errors="coerce",     # invalid → NaT
    dayfirst=True        # handles 30/10/2022 etc
)
item["launch_date"] = item["launch_date"].dt.strftime("%Y-%m-%d")

In [391]:
item["launch_date"]

0     2024-12-07
1            NaT
2            NaT
3            NaT
4            NaT
5            NaT
6            NaT
7            NaT
8            NaT
9            NaT
10           NaT
11           NaT
12           NaT
13           NaT
14           NaT
15           NaT
16           NaT
17    2021-06-01
18           NaT
19           NaT
20           NaT
21           NaT
22           NaT
23           NaT
24           NaT
25           NaT
26           NaT
27           NaT
28           NaT
29           NaT
30           NaT
31           NaT
32           NaT
33           NaT
35           NaT
36           NaT
37           NaT
38           NaT
39           NaT
40           NaT
41           NaT
42           NaT
43           NaT
44           NaT
45           NaT
46           NaT
47           NaT
48           NaT
49           NaT
50           NaT
51           NaT
53           NaT
54           NaT
55           NaT
56           NaT
57           NaT
58           NaT
59           NaT
60           NaT
61           NaT
62           NaT
63           NaT
64           NaT
65           NaT
66           NaT
67           NaT
68           NaT
69           NaT
70           NaT
71           NaT
72           NaT
73           NaT
74           NaT
75           NaT
76           NaT
77           NaT
78           NaT
79           NaT
80           NaT
81           NaT
82           NaT
83           NaT
84           NaT
85           NaT
86           NaT
88           NaT
89           NaT
90           NaT
91           NaT
93           NaT
94    2022-08-11
95           NaT
96           NaT
97           NaT
98           NaT
99           NaT
100          NaT
101          NaT
102          NaT
103          NaT
104          NaT
105          NaT
106          NaT
107          NaT
108          NaT
109          NaT
110          NaT
111          NaT
112          NaT
113          NaT
114          NaT
115          NaT
116   2023-08-10
117          NaT
118          NaT
119          NaT
120          NaT
121          NaT
122          NaT
123          NaT
124          NaT
125          NaT
126          NaT
127          NaT
128          NaT
129          NaT
130   2023-11-02
132          NaT
133          NaT
134          NaT
135   2024-12-04
136          NaT
137          NaT
138          NaT
139          NaT
140   2023-04-01
141          NaT
142          NaT
143          NaT
144          NaT
146          NaT
147          NaT
148          NaT
149          NaT
150          NaT
151          NaT
152          NaT
153          NaT
154          NaT
155          NaT
156          NaT
157          NaT
158          NaT
159          NaT
160          NaT
161          NaT
162          NaT
163          NaT
164          NaT
165          NaT
166          NaT
167          NaT
168          NaT
169          NaT
170   2024-03-05
171          NaT
172          NaT
173          NaT
174          NaT
175          NaT
176   2023-08-09
177          NaT
178          NaT
179          NaT
180          NaT
181          NaT
182          NaT
183          NaT
184   2020-11-02
185          NaT
186          NaT
187          NaT
188          NaT
189          NaT
190          NaT
192          NaT
193          NaT
194          NaT
195          NaT
196   2021-03-06
197          NaT
198          NaT
199          NaT
200          NaT
201          NaT
202          NaT
203          NaT
204          NaT
205          NaT
206          NaT
207          NaT
208          NaT
209          NaT
210          NaT
212          NaT
213          NaT
214   2024-02-06
215          NaT
216          NaT
217          NaT
218          NaT
219          NaT
220          NaT
221          NaT
222          NaT
223          NaT
224          NaT
225          NaT
226          NaT
227          NaT
229          NaT
230          NaT
231          NaT
232          NaT
233          NaT
234          NaT
235          NaT
236          NaT
237          NaT
238          NaT
239          NaT
240          NaT
241          NaT
242          NaT
243          NaT
244          NaT
245          NaT
246          NaT
247          NaT
248          NaT
249          NaT
250          NaT
251          NaT
252          NaT
253          NaT
254          NaT
255          NaT
256          NaT
257          NaT
258          NaT
260          NaT
261   2021-10-07
262          NaT
263          NaT
264          NaT
265          NaT
266          NaT
267          NaT
268          NaT
269          NaT
270          NaT
271          NaT
272   2024-05-08
273          NaT
274          NaT
275          NaT
276          NaT
277          NaT
278          NaT
279          NaT
280          NaT
281          NaT
282          NaT
283          NaT
284   2022-06-08
285          NaT
286          NaT
287          NaT
288          NaT
289          NaT
290          NaT
291          NaT
292          NaT
293          NaT
294          NaT
295          NaT
296          NaT
297          NaT
298          NaT
299          NaT
300          NaT
301          NaT
302          NaT
303          NaT
304          NaT
305          NaT
306          NaT
307          NaT
308          NaT
309          NaT
310          NaT
311          NaT
312          NaT
313          NaT
314          NaT
315          NaT
318          NaT
319          NaT
320   2020-04-06
321          NaT
322          NaT
323          NaT
324          NaT
325          NaT
326          NaT
327          NaT
328          NaT
329          NaT
330          NaT
331          NaT
332          NaT
333          NaT
334          NaT
335          NaT
336          NaT
337          NaT
338          NaT
339          NaT
340   2021-09-07
341          NaT
342          NaT
343          NaT
344          NaT
Name: launch_date, dtype: datetime64[ns]

In [396]:
import pandas as pd
import numpy as np

def clean_price_columns(df):
    df = df.copy()

    cols = ["list_price", "standard_cost"]

    for col in cols:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype(str)
                .str.strip()
                .str.lower()
                # remove currency text
                .str.replace("usd", "", regex=False)
                .str.replace("$", "", regex=False)
                # remove commas (1,200 → 1200)
                .str.replace(",", "", regex=False)
                # replace invalid words with NaN
                .replace(["nan", "none", "null", "n/a", "na", "?", "error", ""], np.nan)
            )

            # convert to numeric
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df.loc[df["list_price"] < 0, "list_price"] = np.nan
    df.loc[df["standard_cost"] < 0, "standard_cost"] = np.nan

    # cost should not exceed price
    df.loc[df["standard_cost"] > df["list_price"], "standard_cost"] = np.nan

    return df

In [397]:
item = clean_price_columns(item)

In [398]:
item[["list_price", "standard_cost"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 344
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   list_price     312 non-null    float64
 1   standard_cost  315 non-null    float64
dtypes: float64(2)
memory usage: 7.8 KB

In [399]:
ratio = (item["standard_cost"] / item["list_price"]).median()

item["standard_cost"] = item["standard_cost"].fillna(
    item["list_price"] * ratio
)

In [400]:
item["list_price"] = item["list_price"].fillna(
    item["standard_cost"] / ratio
)

In [412]:
import numpy as np
import pandas as pd

col = "launch_date"

item[col] = (
    item[col]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace(["", "nan", "none", "null", "n/a", "missing"], np.nan)
    .str.replace(r"(pst|utc|z|\+\d{2}:\d{2})", "", regex=True)
)

In [413]:
item.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 344
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      333 non-null    object
 1   sku             333 non-null    object
 2   category        333 non-null    object
 3   sub_category    333 non-null    object
 4   product_name    333 non-null    object
 5   brand           333 non-null    object
 6   list_price      332 non-null    float64
 7   standard_cost   332 non-null    float64
 8   product_status  333 non-null    object
 9   supplier_name   327 non-null    object
 10  launch_date     333 non-null    object
dtypes: float64(2), object(9)
memory usage: 31.2+ KB

In [405]:
item[col] = pd.to_datetime(
    item[col],
    errors="coerce",
    infer_datetime_format=True
)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_1252\2714250434.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  item[col] = pd.to_datetime(