In [1]:
import pandas as pd
import numpy as np

Basic Access & Indexing

In [ ]:
# Select the age column as a Series.
df=pd.read_csv("pandas_series_dataset.csv")
age=df["age"]
print(age)
print(type(age))

0      56
1      46
2      32
3      60
4      25
       ..
995    23
996    43
997    21
998    36
999    37
Name: age, Length: 1000, dtype: int64
<class 'pandas.core.series.Series'>

In [16]:
# Get the first 10 ages.
Ten_ages=df["age"].head(10)
print("First 10 rows of age column:\n",Ten_ages)
first_10_ages=age.drop_duplicates().sort_values().head(10)
print(first_10_ages)

First 10 rows of age column:
 0    56
1    46
2    32
3    60
4    25
5    38
6    56
7    36
8    40
9    28
Name: age, dtype: int64
94     18
17     19
15     20
43     21
109    22
63     23
38     24
4      25
40     26
71     27
Name: age, dtype: int64

In [ ]:
# Get the last 5 salaries.
df.columns
last_5_salaries=df["salary"].tail(5)

995     77614
996     30281
997     57420
998    110896
999     69030
Name: salary, dtype: int64

In [30]:
# Select ages of employees at index 50, 100, 150.
# I am doing this by using boolen indexing pass list of indexes in list
df.age[[50,100,150]]
# or
df["age"].iloc[[50,100,150]]

50     45
100    61
150    49
Name: age, dtype: int64

In [25]:
# Select the name column using dot notation.
name_col=df.name
print(name_col)

0          Tanya
1      Christine
2          Vicki
3         Monica
4          Erika
         ...
995       Victor
996       Parker
997         Mark
998       Robert
999         Lori
Name: name, Length: 1000, dtype: object

In [27]:
# Check the type of df['salary'].
df["salary"].dtype

dtype('int64')

In [ ]:
#getting the multile columns
df[["age","salary","department"]]

     age  salary department
0     56   79376    Finance
1     46   75587      Sales
2     32   66976      Sales
3     60   97584    Finance
4     25  108477      Sales
..   ...     ...        ...
995   23   77614    Finance
996   43   30281         HR
997   21   57420  Marketing
998   36  110896  Marketing
999   37   69030      Sales

[1000 rows x 3 columns]

Filtering & Boolean Indexing

In [42]:
df.columns

Index(['id', 'name', 'age', 'salary', 'department', 'experience',
       'joining_date', 'rating'],
      dtype='object')

In [44]:
# Find all employees with age > 40.
age_gret_40=df[(df["age"]>40)]["name"]#This will return the true and false correcponding to each row
print(age_gret_40)
#.count->1000 all rows
#.sum return where result is True

0          Tanya
1      Christine
3         Monica
6           Lisa
11       Deborah
         ...
986       Joseph
991      Kenneth
992         Gene
993          Ann
996       Parker
Name: name, Length: 541, dtype: object

In [51]:
# Find all employees with salary > 100000.
age_gret=df[(df["salary"]>100000)].name
print(age_gret)

4            Erika
14             Joy
15     Christopher
25          Ashley
29          Marcus
          ...
984       Michelle
985          Larry
989        Jeffrey
993            Ann
998         Robert
Name: name, Length: 234, dtype: object

In [ ]:
# Select employees from the IT department.
emplyees_from_IT=df[df["department"]=="IT"].name
print(emplyees_from_IT)

9          Zachary
12            Leon
15     Christopher
17           Jerry
21           Jorge
          ...
958          Karen
973          Linda
980          Megan
989        Jeffrey
994        Anthony
Name: name, Length: 205, dtype: object

In [ ]:
# Employees with experience >= 10 years.
exper=df[df["experience"]>=10]
print(exper)

       id       name  age  salary department  experience joining_date  rating
1       2  Christine   46   75587      Sales          13   2018-11-26     2.2
3       4     Monica   60   97584    Finance          18   2016-03-30     3.7
4       5      Erika   25  108477      Sales          13   2020-07-24     4.2
5       6     Daniel   38   72533         HR          37   2019-02-21     2.0
6       7       Lisa   56   31828         HR          35   2019-10-17     3.5
..    ...        ...  ...     ...        ...         ...          ...     ...
994   995    Anthony   22   96504         IT          11   2020-06-28     1.8
995   996     Victor   23   77614    Finance          15   2024-03-24     4.0
997   998       Mark   21   57420  Marketing          24   2018-05-08     3.0
998   999     Robert   36  110896  Marketing          19   2016-12-28     2.8
999  1000       Lori   37   69030      Sales          30   2021-03-18     2.3

[775 rows x 8 columns]

In [66]:
# Employees with rating >= 4.5.
a_rating=df[df["rating"]>=4.5]
print(a_rating)

      id     name  age  salary department  experience joining_date  rating
2      3    Vicki   32   66976      Sales           8   2019-07-28     4.5
9     10  Zachary   28   62254         IT          29   2019-09-13     4.6
29    30   Marcus   44  113524         IT          28   2020-01-25     4.8
40    41   Justin   26   66159         IT          32   2017-11-16     4.9
44    45   Alicia   42   38007  Marketing          34   2025-05-20     4.9
..   ...      ...  ...     ...        ...         ...          ...     ...
959  960    Maria   38   91367         HR          11   2021-01-31     4.7
973  974    Linda   54  118576         IT          13   2023-08-28     4.9
978  979   Carrie   19   85204    Finance          23   2017-11-03     4.6
988  989   Steven   32   30619         HR          15   2019-12-06     4.7
992  993     Gene   62   50337    Finance          34   2022-05-08     4.5

[124 rows x 8 columns]

In [62]:
# Employees with salary between 50000 and 80000.
df[df["salary"].between(50000, 80000)]

       id       name  age  salary department  experience joining_date  rating
0       1      Tanya   56   79376    Finance           6   2024-04-19     2.2
1       2  Christine   46   75587      Sales          13   2018-11-26     2.2
2       3      Vicki   32   66976      Sales           8   2019-07-28     4.5
5       6     Daniel   38   72533         HR          37   2019-02-21     2.0
8       9       Drew   40   50618  Marketing          16   2025-01-20     4.3
..    ...        ...  ...     ...        ...         ...          ...     ...
991   992    Kenneth   43   64707    Finance          12   2024-03-06     2.3
992   993       Gene   62   50337    Finance          34   2022-05-08     4.5
995   996     Victor   23   77614    Finance          15   2024-03-24     4.0
997   998       Mark   21   57420  Marketing          24   2018-05-08     3.0
999  1000       Lori   37   69030      Sales          30   2021-03-18     2.3

[354 rows x 8 columns]

In [65]:
# Employees whose name starts with "A".
a_employees=df[df["name"].str.startswith("A")]
print(a_employees)

      id     name  age  salary department  experience joining_date  rating
22    23  Allison   19   31342  Marketing          27   2024-04-18     4.1
25    26   Ashley   29  109767  Marketing          40   2024-12-08     3.7
31    32   Ashley   45   30235         HR          11   2024-12-26     3.7
44    45   Alicia   42   38007  Marketing          34   2025-05-20     4.9
58    59   Amanda   34  114056         HR          25   2018-03-10     4.9
..   ...      ...  ...     ...        ...         ...          ...     ...
911  912   Alicia   64   95128  Marketing          15   2017-07-23     3.3
944  945   Ashley   25   74965    Finance           5   2021-04-14     4.6
971  972  Anthony   48  109530  Marketing          34   2023-10-31     3.4
993  994      Ann   61  111537    Finance          18   2021-07-01     1.3
994  995  Anthony   22   96504         IT          11   2020-06-28     1.8

[75 rows x 8 columns]

In [70]:
# Employees whose department is not Sales.
other_dep=df[df["department"]!="Sales"]
print(other_dep)

      id     name  age  salary department  experience joining_date  rating
0      1    Tanya   56   79376    Finance           6   2024-04-19     2.2
3      4   Monica   60   97584    Finance          18   2016-03-30     3.7
5      6   Daniel   38   72533         HR          37   2019-02-21     2.0
6      7     Lisa   56   31828         HR          35   2019-10-17     3.5
7      8    David   36   31917    Finance          39   2020-10-24     3.3
..   ...      ...  ...     ...        ...         ...          ...     ...
994  995  Anthony   22   96504         IT          11   2020-06-28     1.8
995  996   Victor   23   77614    Finance          15   2024-03-24     4.0
996  997   Parker   43   30281         HR           9   2024-11-13     1.2
997  998     Mark   21   57420  Marketing          24   2018-05-08     3.0
998  999   Robert   36  110896  Marketing          19   2016-12-28     2.8

[798 rows x 8 columns]

Aggregation & Statistics

In [96]:
# Find mean age.
print("mean",df["age"].mean())
# Find max and min salary.
print("max_salary: ",df["salary"].max())
print("min_salary: ",df["salary"].min())
# Find total experience.
print("total_experience: ",df["experience"].sum())
# Find median rating.
print("median of rating: ",df["rating"].median())
# Find 25th and 75th percentile of salary.
print("25th percentile of salary: ",np.percentile(df["salary"],25))
print("75th percentile of salary: ",np.percentile(df["salary"],75))
# Find standard deviation of age.
print("Standard deviation of age: ",df["age"].std())
# Count number of employees in each department. .size->for countig the number of rows in each department
#value_Count->count the unique values and works only on series not on dataframe
departments=df.groupby("department").size()
print(departments)
# Count unique names.
count_unique_names=df["name"].drop_duplicates().size
print("Count of unique names: ",count_unique_names)
# Find average salary of IT department employees.
avg_salary=(df[df["department"]=="IT"].salary).mean()
print("average salary of it department: ",avg_salary)
# Find the sum of salaries for employees older than 50.
salaries=df[df["age"]>50]["salary"].sum()
print("sum of salaries for employees older than 50: ",salaries)

mean 41.575
max_salary:  119899
min_salary:  30060
total_experience:  20570
median of rating:  2.9
25th percentile of salary:  53803.75
75th percentile of salary:  98028.75
Standard deviation of age:  13.76567720342406
department
Finance      181
HR           192
IT           205
Marketing    220
Sales        202
dtype: int64
Count of unique names:  354
average salary of it department:  76718.8731707317
sum of salaries for employees older than 50:  23458540

Sorting & Ranking

In [109]:
# Sort salaries in descending order.
salary=df["salary"].sort_values(ascending=False)
print("salary: \n",salary)
# Get top 10 highest salaries.
print("Top 10 salaries: \n",salary.head(10))
# Sort employees by age.
df_sorted_by_age = df.sort_values("age")
print("Sort by age: \n",df_sorted_by_age)
# Rank employees by rating (highest rating = rank 1).
rate_by_rating=df.sort_values("rating", ascending=False)
print("Sort by rating: \n",rate_by_rating)
# Sort names alphabetically.
sort_by_name=df["name"].sort_values()
print("Sort alphabetically: \n",sort_by_name)

salary:
 886    119899
468    119613
370    119599
356    119563
532    119431
        ...
996     30281
31      30235
147     30126
53      30077
399     30060
Name: salary, Length: 1000, dtype: int64
Top 10 salaries:
 886    119899
468    119613
370    119599
356    119563
532    119431
379    119399
716    119186
226    119106
412    118929
48     118861
Name: salary, dtype: int64
Sort by age:
       id      name  age  salary department  experience joining_date  rating
636  637      Ryan   18   99274  Marketing          24   2020-01-15     2.4
518  519   Raymond   18   62733         HR          18   2016-11-25     4.8
94    95   Herbert   18   81356    Finance          18   2023-08-31     4.8
398  399     Paula   18   64008  Marketing          14   2018-05-26     5.0
99   100     James   18   62154         IT          13   2022-12-01     4.9
..   ...       ...  ...     ...        ...         ...          ...     ...
481  482  Michelle   65   36640         HR          11   2025-10-29     3.0
453  454   Charles   65   41122         IT          29   2017-07-15     2.8
962  963   Valerie   65   74738         HR           2   2023-04-29     1.2
574  575       Ann   65  114386  Marketing          32   2023-08-17     3.2
556  557       Amy   65   91665      Sales          13   2018-06-22     3.0

[1000 rows x 8 columns]
Sort by rating:
       id      name  age  salary department  experience joining_date  rating
405  406    Ronald   32   75186  Marketing           0   2017-11-12     5.0
410  411    Hannah   40  115469      Sales          22   2024-12-06     5.0
927  928      Mark   42   72229         IT          16   2021-02-25     5.0
505  506   Matthew   45  103972      Sales          28   2020-01-07     5.0
434  435     Kelly   33  100855         HR          37   2024-06-22     5.0
..   ...       ...  ...     ...        ...         ...          ...     ...
110  111   Michael   59   59486         HR          40   2023-09-07     1.0
101  102     Kerry   25   32336         HR          19   2017-07-15     1.0
274  275  Brittany   49  114458  Marketing          12   2024-06-03     1.0
915  916    Robert   52   61585         IT           7   2018-08-06     1.0
316  317   Garrett   34   58529  Marketing          36   2021-04-17     1.0

[1000 rows x 8 columns]
Sort alphabetically:
 450      Aaron
588      Aaron
270       Adam
304     Adrian
535     Adrian
        ...
712    Zachary
81     Zachary
333    Zachary
626    Zachary
835    Zachary
Name: name, Length: 1000, dtype: object

Arithmetic & Transformations

In [ ]:
# Increase all salaries by 10%.
df["salary"]= df["salary"].apply(lambda x: x*0.10)
#second way
df["salary"] = df["salary"] * 1.10
print(df["salary"])
# Calculate salary per year of experience (avoid division by zero).
df["salary_per_experience"] = df["salary"] / df["experience"].replace(0, np.nan)
print(df[["name", "salary", "experience", "salary_per_experience"]])
# Convert age to months. multiply the number of years by 12 and add the remaining months
df["age"]=df["age"]*12
print("Age to Months",df["age"])
# Round rating to nearest integer.
df["rating_rounded"]=np.round(df["rating"], 0).astype(int)
print(df[["rating", "rating_rounded"]])
# Apply a function to double the experience.
df["experience"]= df["experience"].apply(lambda x: x*2)
#other way
df["experience"]= df["experience"]*2
print(df["experience"])

0      0.001701
1      0.001620
2      0.001436
3      0.002092
4      0.002325
         ...
995    0.001664
996    0.000649
997    0.001231
998    0.002377
999    0.001480
Name: salary, Length: 1000, dtype: float64
          name    salary           experience  salary_per_experience
0        Tanya  0.001701        2821109907456           6.031297e-16
1    Christine  0.001620   665416609183179841           2.434978e-21
2        Vicki  0.001436      281474976710656           5.100596e-18
3       Monica  0.002092 -7687677419372609536          -2.720977e-22
4        Erika  0.002325   665416609183179841           3.494504e-21
..         ...       ...                  ...                    ...
995     Victor  0.001664  6568408355712890625           2.532920e-22
996     Parker  0.000649     1853020188851841           3.502931e-19
997       Mark  0.001231 -2936065482068852736          -4.192170e-22
998     Robert  0.002377 -6706491611731658175          -3.544557e-22
999       Lori  0.001480 -6009704086096510976          -2.462217e-22

[1000 rows x 4 columns]
Age to Months 0      24078974976
1      19779158016
2      13759414272
3      25798901760
4      10749542400
          ...
995     9889579008
996    18489212928
997     9029615616
998    15479341056
999    15909322752
Name: age, Length: 1000, dtype: int64
     rating  rating_rounded
0       2.2               2
1       2.2               2
2       4.5               4
3       3.7               4
4       4.2               4
..      ...             ...
995     4.0               4
996     1.2               1
997     3.0               3
998     2.8               3
999     2.3               2

[1000 rows x 2 columns]
0                   15917322219892801768783872
1         885558527553681396608626384297570562
2               158456325028528675187087900672
3      118200768208663010786322746068636270592
4         885558527553681396608626384297570562
                        ...
995     86287976654797839000821113586425781250
996            6867367640585024969315698178562
997     17240961029992409214052916406509371392
998     89954059476454188294098927070088661250
999     72233086404890200419262820480976945152
Name: experience, Length: 1000, dtype: object

String Operations

In [137]:
# Convert all names to uppercase.
df["upper"]=df["name"].str.upper()
print(df["upper"])
# Find employees whose name contains "n".
df[df["name"].str.contains("n", case=False)]
# Count length of each name.
df["name_length"] = df["name"].str.len()
print(df["name_length"])
# Check if names start with a vowel. #list not applicable here
df[df["name"].str.startswith(("a","e","i","o","u","A","E","I","O","U"))]
# Create a Series of name initials. str.strip() removes spaces
df["initials"]=df["name"].str[0]
df["initials"]

0          TANYA
1      CHRISTINE
2          VICKI
3         MONICA
4          ERIKA
         ...
995       VICTOR
996       PARKER
997         MARK
998       ROBERT
999         LORI
Name: upper, Length: 1000, dtype: object
0      5
1      9
2      5
3      6
4      5
      ..
995    6
996    6
997    4
998    6
999    4
Name: name_length, Length: 1000, dtype: int64

0      T
1      C
2      V
3      M
4      E
      ..
995    V
996    P
997    M
998    R
999    L
Name: initials, Length: 1000, dtype: object

Missing Values (simulate a few if needed)

In [145]:
# 40.	Check for missing values in salary.
na_values=df[df["salary"].isna()]
# 41.	Fill missing salaries with the mean salary.
df["salary"] = df["salary"].fillna(df["salary"].mean())
# 42.	Drop rows where rating is missing.
df = df[df["rating"].notna()]
# 43.	Replace all ratings below 2.0 with 2.0.
df["rating"] = df["rating"].apply(lambda x: 2.0 if x < 2.0 else x)
df["rating"] = df["rating"].clip(lower=2.0)
df["rating"]

0      2.2
1      2.2
2      4.5
3      3.7
4      4.2
      ...
995    4.0
996    2.0
997    3.0
998    2.8
999    2.3
Name: rating, Length: 1000, dtype: float64

Cumulative & Window Functions

In [150]:
# Compute cumulative sum of salaries.
np.cumsum(df["salary"])
#pandas way
df["salary_cumsum"] = df["salary"].cumsum()
print(df["salary_cumsum"])
# Compute cumulative maximum of ratings.
df["rating_cumrating"] = df["rating"].cummax()
print(df["rating_cumrating"])
# Find rolling mean of salary with window size 5.
df["salary_roll_mean"] = df["salary"].rolling(window=5).mean()
print(df["salary_roll_mean"])

0      0.001701
1      0.003322
2      0.004757
3      0.006849
4      0.009175
         ...
995    1.605084
996    1.605733
997    1.606964
998    1.609341
999    1.610821
Name: salary_cumsum, Length: 1000, dtype: float64
0      2.2
1      2.2
2      4.5
3      4.5
4      4.5
      ...
995    5.0
996    5.0
997    5.0
998    5.0
999    5.0
Name: rating_cumrating, Length: 1000, dtype: float64
0           NaN
1           NaN
2           NaN
3           NaN
4      0.001835
         ...
995    0.001718
996    0.001570
997    0.001601
998    0.001598
999    0.001480
Name: salary_roll_mean, Length: 1000, dtype: float64

Indexing & Selection

In [ ]:
# Set id as the index and select the salary of employee with id=500.
df=pd.read_csv("pandas_series_dataset.csv").set_index("id")
salary_500=df.loc[500, "salary"] #label
salary_500
# Reset the index.
df.reset_index(inplace=True)
# Access salary using .iloc[100]. in iloc must pass index/ uses positions, never index labels.
df.iloc[100, 3] #100 row , 3 column
# Access salary using .loc[100]. loc uses labels 
df.loc[100, "salary"]

np.int64(62154)

| Method                       | Indexing Type  | Example                        | Notes                     |
| ---------------------------- | -------------- | ------------------------------ | ------------------------- |
| `.loc[row_label, col_label]` | Label-based    | `df.loc[500, "salary"]`        | Uses index label (id=500) |
| `.iloc[row_pos, col_pos]`    | Position-based | `df.iloc[100, 3]`              | 100th row, 4th column     |
| `reset_index()`              | Resets index   | `df.reset_index(inplace=True)` | Makes old index a column  |