In [4]:
import pandas as pd
import numpy as np

how to prove 
series-> 1D
DataFrame-> 2D

In [8]:
#can we make multi index
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
# a([])

In [9]:
# correct way
#multi indexing series uses multilevel indexing also known as hierarchal indexing
# For creating there are two ways
# 1.pd.MultiIndex.from_tuples()
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex.levels #decouples
multiindex.levels[0]
multiindex.levels[1]
# 1.pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse', 'ece'], [2019, 2020, 2021, 2022]]) #formed by cartesian prod

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [10]:
s=pd.Series([1,2,3,4,5,6,7,8], index=multiindex).reset_index()
s

  level_0  level_1  0
0     cse     2019  1
1     cse     2020  2
2     cse     2021  3
3     cse     2022  4
4     ece     2019  5
5     ece     2020  6
6     ece     2021  7
7     ece     2022  8

In [11]:
# How to fetch from this series 
#faida yeh ha you can fetch kisi bhi trhn se
s
s[('cse',2022)]
s['cse']
s.shape

KeyError: ('cse', 2022)

In [15]:
#it is logical to represent through dataframes
#unstack
temp=s.unstack()
temp

level_0  0     cse
         1     cse
         2     cse
         3     cse
         4     ece
         5     ece
         6     ece
         7     ece
level_1  0    2019
         1    2020
         2    2021
         3    2022
         4    2019
         5    2020
         6    2021
         7    2022
0        0       1
         1       2
         2       3
         3       4
         4       5
         5       6
         6       7
         7       8
dtype: object

multiindex_series->dataframe use->unstack
dataframe->multiindex_series- use->stack

In [14]:
temp.stack()

AttributeError: 'Series' object has no attribute 'stack'

Why should we use multi index series when we can do our work with dataframes
higher dimensional data into lower dimensional object (series ko use kr ke 2D ki form me dekhaya) 10D can be represented into 2D

MultiindexDataFrame

In [16]:

branch_df=pd.DataFrame(
    [
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12],
    [13,14],
    [15,16],
],
columns=['avg_package','students'],
index=multiindex
)
branch_df
# branch_df.loc['cse']

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

Pandas treat index and column same means
midf form->rows
mi_df->col

In [ ]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0